### PR TITLE
Addresses #1

### PR DESCRIPTION
**Pull request by KoryNunn**
Will need a major version bump

### CODE REVIEW

**Comment by KoryNunn** [comment]
Using falsey and typeof check because it satisfies all cases other than Buffer, which we probably don't care about.

**Comment by KoryNunn** [comment]
I'm not sure about using AES-256-CTR. Doesn't seem to be on this windows box. Maybe it ships with node?

**Comment by SN4T14** [comment]
>it satisfies all cases other than Buffer, which we probably don't care about.

That's for the user to decide, there's a reason it's supported, various Node APIs return a buffer, and not all buffers are valid UTF-8.

>I'm not sure about using AES-256-CTR. Doesn't seem to be on this windows box.

What's the output of crypto.getCiphers() on your machine?

**Comment by paragonie-scott** [comment]
No HMAC?

**Pull request closed without merging**
